### ISSUE TITLE
[Feature]: 服务器无代理无法访问glados.rocks

### ISSUE THREAD

**Issue by Hwenray** [hennessey-v/GlaDOS_Checkin_ql#10]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

服务器无代理无法访问glados.rocks

### 描述你想要的解决方案

建议增加可以切换的配置项或者更改为glados.one等无需vpn即可访问的地址

### 附加信息

（其实就是懒得手动改辣:p

**Comment by Hwenray** [comment]
> ### 解决方案检查
> * [x]  我已搜索issue列表([https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=](https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=%E2%9C%93&q=))，但没有发现类似的问题
> 
> ### 问题描述
> 服务器无代理无法访问glados.rocks
> 
> ### 描述你想要的解决方案
> 建议增加可以切换的配置项或者更改为glados.one等无需vpn即可访问的地址
> 
> ### 附加信息
> （其实就是懒得手动改辣:p

目前手动更改后可以正常运行，可以解决 #5 遇到的问题

**Comment by RaineaAN** [comment]
感谢反馈！稍后加个配置项吧，我的服务器一直是无代理环境正常运行，还以为大家都正常😋
