### ISSUE TITLE
[Bug]: 面板上一直错误，本地正常

### ISSUE THREAD

**Issue by Arnnoo** [hennessey-v/GlaDOS_Checkin_ql#11]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，并没有发现类似的问题

### 青龙版本

2.16.0

### 操作系统

CentOS-7.9.2011-x64

### 问题反馈

青龙面板上，我安装了requests模块，上传了checkin和config文件，环境变量和config文件配置正确，删除了通知部分，但是运行一直失败：
签到失败，请检查网络：'latin-1' codec can't encode character '\u2018' in position 0: ordinal not in range(256)

本地pycharm同样配置正常签到，青龙面板上其他的签到脚本正常，端口正常开放，
百度查了下报错是编码问题？刚学python求解

**Comment by RaineaAN** [comment]
可能是你的编辑器将文件自动编码为**latin-1**格式。
建议把修改后的文件编码为**UTF-8**格式，再次上传即可解决问题。

更加推荐使用命令拉库后，使用青龙的**脚本编辑**功能修改代码
```
git clone https://ghproxy.com/https://github.com/hennessey-v/GlaDOS_Checkin_ql.git GlaDOS_Checkin
```

------------------------------
稍后我会加入关闭通知的功能，增加用户体验。最近比较忙，不能即时优化功能😔

**Comment by Arnnoo** [comment]
多谢，本地正常执行的脚本重新上传了下正常了，通知哈哈我直接删除了，多谢大佬

**Comment by RaineaAN** [comment]
😊
