### ISSUE TITLE
青龙更新后提示没有Cookies From config

### ISSUE THREAD

**Issue by JackA1ltman** [hennessey-v/GlaDOS_Checkin_ql#13]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，并没有发现类似的问题

### 青龙版本

2.15.16

### 操作系统

Alpine Linux v3.18

### 问题反馈

如图所示
![Screenshot_20230819-104512](https://github.com/hennessey-v/GlaDOS_Checkin_ql/assets/82563979/50573be5-9e87-48e7-9ba7-8fb195a4fd31)

**Comment by RaineaAN** [comment]
你用的青龙面板吗，cookie保存在面板环境变量里还是存在config.py文件里

> 如果是存在config.py文件里，给我看一下config.py文件的配置。（cookie记得打码）

**Comment by JackA1ltman** [comment]
找到问题了，是cookie的问题😭，谢谢开发者的回复
