### ISSUE TITLE
[Bug]: 企业微信消息推送失败

### ISSUE THREAD

**Issue by sailcom** [hennessey-v/GlaDOS_Checkin_ql#2]
### 解决方案检查

- [x] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，并没有发现类似的问题

### 青龙版本

2.15.6

### 操作系统

Linux

### 问题反馈

反馈一处代码错误。
/sendNotify.py 文件第289行，应修改为：
`if not media_id:`
因为在286行已经定义了，当 QYWX_AM_AY 不存在时，给media_id赋空值。
所以289行应该是media_id为空的判断。
否则会导致企业微信发送失败【推送失败！错误信息如下：invalid media_id】
如下图所示：
![Snipaste_2023-02-17_11-02-14](https://user-images.githubusercontent.com/42264621/219540596-af355348-e3b7-429d-8cab-77b4415cdb15.png)

**Comment by RaineaAN** [comment]
您好！最新一次提交已经修复了这项错误
非常感谢您的反馈！😊

**Comment by sailcom** [comment]
效率之高，赞一个~
