### ISSUE TITLE
[Bug]: 推送配置

### ISSUE THREAD

**Issue by byeice** [hennessey-v/GlaDOS_Checkin_ql#3]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，并没有发现类似的问题

### 青龙版本

2.10

### 操作系统

Ubuntu

### 问题反馈

大佬，通知推送在哪里配置，如何配置？
目前青龙面板可以正常运行，推送通知不知道怎么配置。。。。
多谢。

**Comment by RaineaAN** [comment]
你好，在青龙面板**config.sh**配置文件中配置即可，如何配置请参考文件内描述信息

#### 拓展:
如果推送信息需要和其他脚本推送区分开可以按照以下方法配置：
(这里以企业微信应用推送为例，其他方式同理)
```
## 指定的脚本单独推送
case $1 in
    *checkin.py ) # GlaDOS推送
        export QYWX_AM="本项目签到脚本企业微信应用推送参数"
        ;;
    *)
        export QYWX_AM="其他项目的企业微信推送参数"
        ;;
esac
```
