### ISSUE TITLE
他这个延迟会员时间 ，那么流量也是固定的吗？[Feature]: 

### ISSUE THREAD

**Issue by zhugui00** [hennessey-v/GlaDOS_Checkin_ql#4]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

他这个延迟会员时间 ，那么流量也是固定的吗？

### 描述你想要的解决方案

他这个延迟会员时间 ，那么流量也是固定的吗？

**Comment by RaineaAN** [comment]
每天签到续费当前会员套餐的时间，流量是按月刷新的

**Comment by zhugui00** [comment]
懂了 还是得先搞一月会员，并已经搞了  多谢回答！
