### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dark748001** [hennessey-v/GlaDOS_Checkin_ql#5]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，并没有发现类似的问题

### 青龙版本

2.10.2

### 操作系统

群辉

### 问题反馈

已获取并使用Env环境 Cookie
共获取到2个GlaDOS账号Cookie

脚本执行时间(北京时区): 2023/06/05 16:09:54

签到失败，请检查网络：('Connection aborted.', OSError(22, 'Invalid argument'))
签到失败，请检查网络：('Connection aborted.', OSError(22, 'Invalid argument'))
签到失败，请检查账户信息以及网络环境
推送成功！

### 附加信息

已获取并使用Env环境 Cookie
共获取到2个GlaDOS账号Cookie

脚本执行时间(北京时区): 2023/06/05 16:09:54

签到失败，请检查网络：('Connection aborted.', OSError(22, 'Invalid argument'))
签到失败，请检查网络：('Connection aborted.', OSError(22, 'Invalid argument'))
签到失败，请检查账户信息以及网络环境
推送成功！

**Comment by RaineaAN** [comment]
很抱歉，我不能复现这个bug，因此我不能确定问题所在。脚本在我的网络环境中一切正常。
如果你使用的容器运行的脚本，请检查容器内的网络情况。如果你使用了代理，请检查代理环境并尝试

**Comment by Hwenray** [comment]
> ### 解决方案检查
> * [x]  我已搜索issue列表([https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=](https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=%E2%9C%93&q=))，并没有发现类似的问题
> 
> ### 青龙版本
> 2.10.2
> 
> ### 操作系统
> 群辉
> 
> ### 问题反馈
> 已获取并使用Env环境 Cookie 共获取到2个GlaDOS账号Cookie
> 
> 脚本执行时间(北京时区): 2023/06/05 16:09:54
> 
> 签到失败，请检查网络：('Connection aborted.', OSError(22, 'Invalid argument')) 签到失败，请检查网络：('Connection aborted.', OSError(22, 'Invalid argument')) 签到失败，请检查账户信息以及网络环境 推送成功！
> 
> ### 附加信息
> 已获取并使用Env环境 Cookie 共获取到2个GlaDOS账号Cookie
> 
> 脚本执行时间(北京时区): 2023/06/05 16:09:54
> 
> 签到失败，请检查网络：('Connection aborted.', OSError(22, 'Invalid argument')) 签到失败，请检查网络：('Connection aborted.', OSError(22, 'Invalid argument')) 签到失败，请检查账户信息以及网络环境 推送成功！

你这个应该可以通过替换项目内的"https://glados.rocks"为"https://glados.one"来解决
