### ISSUE TITLE
[Feature]: 希望增加飞书通知的功能

### ISSUE THREAD

**Issue by mohan9898** [hennessey-v/GlaDOS_Checkin_ql#6]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望增加飞书通知的功能

### 描述你想要的解决方案

希望增加飞书通知的功能

### 附加信息

/

**Comment by RaineaAN** [comment]
你好，已经增加了飞书机器人等多种推送方式。感谢建议！

**Comment by mohan9898** [comment]
飞书 推送失败！错误信息如下：
 {'code': 19024, 'data': {}, 'msg': 'Key Words Not Found'}

**Comment by RaineaAN** [comment]
> 飞书 推送失败！错误信息如下： {'code': 19024, 'data': {}, 'msg': 'Key Words Not Found'}

来自飞书自定义机器人使用指南：https://open.feishu.cn/document/client-docs/bot-v3/add-custom-bot

```
设置关键词后，如果发送请求时自定义关键词校验失败，则会返回以下信息。

// 关键词校验失败
{
     "code": 19024,
     "msg": "Key Words Not Found"
}
```
请根据指南配置正确的关键词

**Comment by mohan9898** [comment]
感谢，已解决
