### ISSUE TITLE
[Bug]: 解析登录结果失败：'data'

### ISSUE THREAD

**Issue by RepentStar** [hennessey-v/GlaDOS_Checkin_ql#7]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，并没有发现类似的问题

### 青龙版本

正式版 v2.15.17

### 操作系统

Ubuntu 22

### 问题反馈

```
已获取并使用Env环境 Cookie
共获取到2个GlaDOS账号Cookie

脚本执行时间(北京时区): 2023/07/26 17:13:23

解析登录结果失败：'data'
解析登录结果失败：'data'
签到失败，请检查账户信息以及网络环境
GlaDOS签到通知

签到失败，请检查账户信息以及网络环境
```
按照readme安装配置脚本，首次运行提示没有requests模块，自行去“依赖管理”安装了`requests`。

**Comment by RepentStar** [comment]
问题已经解决，解决方法：把提取到的cookie按如下整理再填入变量：
```
koa:sess=***;koa:sess.sig=***
```
希望作者把这一步补充进readme免得有人像我一样。
另外希望在安装第一步添加说明依赖项`requests`

**Comment by RaineaAN** [comment]
> 问题已经解决，解决方法：把提取到的cookie按如下整理再填入变量：
> 
> ```
> koa:sess=***;koa:sess.sig=***
> ```
> 
> 希望作者把这一步补充进readme免得有人像我一样。 另外希望在安装第一步添加说明依赖项`requests`

好的，感谢反馈！
