### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by geqianqianqian** [hennessey-v/GlaDOS_Checkin_ql#8]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，并没有发现类似的问题

### 青龙版本

2.11.3

### 操作系统

centos7.6

### 问题反馈

提示签到结果：oops, token error
天数没有增加

### 附加信息

提示签到结果：oops, token error
天数没有增加

**Comment by RaineaAN** [comment]
能提供更多信息吗
看一下token的格式

**Comment by geqianqianqian** [comment]
![QQ截图20230727154701](https://github.com/hennessey-v/GlaDOS_Checkin_ql/assets/75306085/55571dca-f17b-46ef-97a0-c943b79daaf4)

**Comment by geqianqianqian** [comment]
> 能够提供更多信息吗 看一下令牌的格式

好的

**Comment by RaineaAN** [comment]
> > 能够提供更多信息吗 看一下令牌的格式
> 
> 好的

已修复，请更新脚本重新运行

另外，COOKIE需按 '**koa:sess=xxxxxxxxx; koa:sess.sig=xxxx;**' 的格式填入。即结尾处也有一个分号
