### ISSUE TITLE
[Feature]: 如果可以增加一个环境变量，正常情况不推送消息就好了

### ISSUE THREAD

**Issue by yacon** [hennessey-v/GlaDOS_Checkin_ql#9]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/hennessey-v/GlaDOS_Checkin_ql/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

如题，不知道能不能实现默认推送消息，可以通过环境变量设置，非正常响应才推送

### 描述你想要的解决方案

默认推送消息，可以通过环境变量设置，非正常响应才推送

**Comment by RaineaAN** [comment]
感谢反馈！稍后会加一个通知配置，来实现禁用通知，全部通知和仅推送异常信息

**Comment by yacon** [comment]
谢谢😊

**Comment by hldh214** [comment]
https://github.com/hldh214/GlaDOS_Checkin_ql/commit/bd7d67152f03630f3a7b837d9ab2e44638c47301
我来抛砖引玉一下.
